import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        'primary': '#000000',
        'on-primary': '#e5e2e1',
        'primary-fixed': '#5f5e5e',
        'primary-fixed-dim': '#474746',
        'primary-container': '#3c3b3b',
        'on-primary-container': '#ffffff',
        'on-primary-fixed': '#ffffff',
        'on-primary-fixed-variant': '#e5e2e1',
        'secondary': '#5e5e5e',
        'on-secondary': '#ffffff',
        'secondary-container': '#d4d4d4',
        'on-secondary-container': '#1b1b1b',
        'secondary-fixed': '#c6c6c6',
        'secondary-fixed-dim': '#ababab',
        'on-secondary-fixed': '#1b1b1b',
        'on-secondary-fixed-variant': '#3b3b3b',
        'tertiary': '#3b3b3b',
        'on-tertiary': '#e2e2e2',
        'tertiary-container': '#747474',
        'on-tertiary-container': '#ffffff',
        'tertiary-fixed': '#5e5e5e',
        'tertiary-fixed-dim': '#474747',
        'on-tertiary-fixed': '#ffffff',
        'on-tertiary-fixed-variant': '#e2e2e2',
        'surface': '#f9f9f9',
        'surface-dim': '#dadada',
        'surface-bright': '#f9f9f9',
        'surface-variant': '#e2e2e2',
        'surface-tint': '#5f5e5e',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f3',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#474747',
        'background': '#ffffff',
        'on-background': '#1a1c1c',
        'outline': '#777777',
        'outline-variant': '#c6c6c6',
        'inverse-surface': '#2f3131',
        'inverse-on-surface': '#f1f1f1',
        'inverse-primary': '#c8c6c5',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#410002',
        'accent': '#e00000',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        display: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}

export default config
